[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["php82", "php82Extensions.intl", "php82Extensions.zip", "nodejs_20"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev", "npm install"]

[phases.build]
cmds = ["npm run build"]
